import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Chess, DEFAULT_POSITION } from 'chess.js';
import type { ChessHelperAPI, Snapshot, Token, Settings, Side, Orientation, Placement, Source, CaptureSelection } from '../shared/contracts';
import { placementsOf, placementFen, displayScore } from '../core/position';
import { Board, GLYPHS } from './Board';
import { BoardCapture } from './capture';
import { installMouseHitTesting } from './mouse';
import './styles.css';
declare global { interface Window { chessHelper?: ChessHelperAPI } }
const api = window.chessHelper;
const tokenOf = (state: Snapshot): Token => ({ sessionId: state.status.sessionId, revision: state.status.revision });
function useSnapshot() {
  const [state, setState] = useState<Snapshot | null>(null);
  useEffect(() => { if (!api) return; const unsubscribe = api.subscribe(setState); void api.snapshot().then(setState); return unsubscribe; }, []);
  return state;
}
function useAction() { const [error,setError] = useState(''); const [busy,setBusy] = useState(false); const run = async (action: () => Promise<unknown>) => { setError(''); setBusy(true); try { await action(); } catch(error) { setError(error instanceof Error ? error.message.replace(/^Error invoking remote method '[^']+': (Error: )?/, '') : 'The action could not be completed. Try again.'); } finally { setBusy(false); } }; return { error,busy,run }; }
function ErrorMessage({ message }: { message: string }) { return message ? <p className="error" role="alert">{message}</p> : null; }
function SideControls({ side, orientation, onSide, onOrientation }: { side: Side; orientation: Orientation; onSide: (side: Side) => void; onOrientation: (orientation: Orientation) => void }) {
  return <div className="fields-row"><label>Coach<select value={side} onChange={e => onSide(e.target.value as Side)}><option value="w">White</option><option value="b">Black</option></select></label><label>Board orientation<select value={orientation} onChange={e => onOrientation(e.target.value as Orientation)}><option value="white-bottom">White at bottom</option><option value="black-bottom">Black at bottom</option></select></label></div>;
}
function Coach({ state }: { state: Snapshot }) {
  const { error,busy,run } = useAction(); const position = state.position;
  const turn = position ? new Chess(position.fen).turn() : null;
  const candidates = state.analysis?.candidates ?? [];
  const placements = state.observation && state.status.state === 'Needs correction' ? state.observation.placements : position ? placementsOf(position.fen) : [];
  useEffect(() => { if (!api) return; const capture = new BoardCapture(api); const unsub = api.onCapture(command => void capture.receive(command)); const mouse = installMouseHitTesting(api); if (state.selection && (state.running || state.status.state === 'Reading board')) void capture.receive({ ...tokenOf(state), action: state.running ? 'start' : 'sample', selection: state.selection }); return () => { unsub(); mouse(); capture.stop(); }; }, []);
  return <main className="coach-shell" data-panel>
    <header className="coach-header"><span className="app-symbol" aria-hidden="true">♞</span><div><strong>Chess Helper</strong><span className="micro">Permitted practice · local Stockfish</span></div><button className="icon-button no-drag" aria-label="Hide Helper" title="Hide Helper" onClick={() => void api!.hide()}>−</button></header>
    <div className="status-line" role="status"><span className={`status-dot ${state.status.state === 'Ready' ? 'ready' : ''}`} />{state.status.state}<span className="revision">#{state.status.revision}</span></div>
    <p className="status-message">{state.status.message}</p>
    <div className="board-section"><Board placements={placements} orientation={position?.orientation ?? state.selection?.orientation ?? 'white-bottom'} arrow={candidates[0]?.id} uncertain={state.observation?.uncertainSquares}/><div className="position-meta"><strong>{turn ? `${turn === 'w' ? 'White' : 'Black'} to move` : 'No confirmed position'}</strong><span>{position ? `Coaching ${position.coachedSide === 'w' ? 'White' : 'Black'}` : 'Confirm a board to begin'}</span>{position && !position.historyComplete && <span>Earlier history unknown</span>}</div></div>
    {candidates.length > 0 && <section aria-label="Engine recommendations">
      <div className="section-label">{turn !== position?.coachedSide ? 'EXPECTED OPPONENT CONTINUATIONS' : 'ENGINE RECOMMENDATION'}<span>White’s score</span></div>
      {candidates.map((candidate,index) => { const explanation = state.explanations.find(entry => entry.candidateId === candidate.id); return <article className={`candidate ${index === 0 ? 'primary-candidate' : ''}`} key={candidate.id}>
        <div className="candidate-heading"><strong>{candidate.san}</strong><span className="score">{displayScore(candidate.score)}</span><span className="depth">Depth {candidate.depth}</span></div>
        <p className="move-description">{candidate.plain}</p>
        {explanation ? <><p>{explanation.explanation}</p><p className="reply"><b>Engine-expected reply:</b> {candidate.variation[1]?.san ?? 'No reply in this line'}</p>{index === 0 && <div className="tradeoffs"><p><b>Benefit</b> {explanation.benefit}</p><p><b>Watch for</b> {explanation.drawback}</p></div>}</> : <p className="muted">{state.explanationState === 'loading' ? 'Adding an explanation…' : 'Explanation unavailable'}</p>}
        <details><summary>Variation · {candidate.variation.length} moves</summary><p className="variation">{candidate.variation.map((move,i) => <span key={i}>{move.san} </span>)}</p></details>
      </article>; })}
      <p className="disclosure">Stockfish’s recommendation at the displayed depth. AI explanations interpret the engine’s evidence.</p>
      {state.explanationState === 'unavailable' && <button disabled={busy || !state.hasApiKey} onClick={() => void run(() => api!.retryExplanation(tokenOf(state)))}>Retry Explanation</button>}
    </section>}
    {!position && <div className="empty-state"><strong>A second pair of eyes for your board.</strong><p>Select a browser window or enter a position. You’ll confirm the pieces and special-move rights before receiving advice.</p><button className="accent-button" onClick={() => void run(() => api!.openWindow('selection'))}>Select Board</button></div>}
    {state.analysis?.terminal && <p className="terminal">{state.analysis.terminal === 'checkmate' ? 'Checkmate' : 'Stalemate'} — no legal moves.</p>}
    <ErrorMessage message={error}/>
    {state.status.error?.code === 'engine' && <button onClick={() => void run(() => api!.restartEngine(tokenOf(state)))}>Restart Engine</button>}
    {state.shortcutConflicts.length > 0 && <p className="error">Shortcut conflicts: {state.shortcutConflicts.join(', ')}. Rebind in Settings.</p>}
    <footer className="coach-actions"><button disabled={busy} onClick={() => void run(() => state.running ? api!.pause(tokenOf(state)) : api!.start(tokenOf(state)))}>{state.running ? 'Pause' : 'Start'}</button><button disabled={busy} onClick={() => void run(() => api!.rescan(tokenOf(state)))}>Rescan</button><button onClick={() => void run(() => api!.openWindow('correction'))}>Correct Position</button><button onClick={() => void run(() => api!.openWindow('settings'))}>Settings</button></footer>
    <p className="bottom-note">Arrows appear only here. Moves are always yours to play.</p>
  </main>;
}
function SettingsView({ state }: { state: Snapshot }) {
  const [settings,setSettings] = useState<Settings>(state.settings); const [key,setKey] = useState(''); const [changeKey,setChangeKey] = useState(false); const [saved,setSaved] = useState(false); const {error,busy,run} = useAction();
  return <main className="form-shell"><header><h1>Chess Helper Settings</h1><p>Choose how your board is read and your moves are explained.</p></header>
    <form onSubmit={e => { e.preventDefault(); void run(async () => { await api!.saveSettings({ ...tokenOf(state), settings, ...(changeKey ? { apiKey: key.trim() } : {}) }); setKey(''); setChangeKey(false); setSaved(true); }); }}>
      <section><h2>Cloud AI</h2>{(['recognition','explanations'] as const).map(kind => <fieldset key={kind}><legend>{kind === 'recognition' ? 'Board recognition' : 'Move explanations'}</legend><div className="fields-row"><label>Model<select value={settings[kind].model} onChange={e => setSettings({ ...settings, [kind]: { ...settings[kind], model: e.target.value } })}><option value="gpt-6.1-sol">GPT-6.1 Sol</option><option value="gpt-6-astra">GPT-6 Astra</option></select></label><label>Thinking<select value={settings[kind].effort} onChange={e => setSettings({ ...settings, [kind]: { ...settings[kind], effort: e.target.value } })}>{['low','medium','high','xhigh'].map(effort => <option key={effort} value={effort}>{effort === 'xhigh' ? 'Extra high' : effort[0].toUpperCase() + effort.slice(1)}</option>)}</select></label></div></fieldset>)}
      <label>OpenAI API key <span className="muted">{state.hasApiKey ? 'Saved securely' : 'No key saved'}</span><input type="password" value={key} autoComplete="off" placeholder="Enter a new key" onChange={e => { setKey(e.target.value); setChangeKey(true); setSaved(false); }}/></label><p className="muted">Only the board crop is uploaded for recognition. Explanations receive the confirmed position and engine lines. API usage is billed to your account.</p>{state.hasApiKey && <button type="button" onClick={() => { setKey(''); setChangeKey(true); }}>Remove Saved Key on Save</button>}</section>
      <section><h2>Tracking</h2><label className="checkbox"><input type="checkbox" checked={settings.automaticTracking} disabled={!state.trackingQualified} onChange={e => setSettings({ ...settings, automaticTracking: e.target.checked })}/>Track automatically at two samples per second</label>{!state.trackingQualified && <p className="muted">Automatic tracking is awaiting recorded Chess.com and Lichess fixture validation. Use Rescan to read a board manually.</p>}</section>
      <section><h2>Keyboard shortcuts</h2>{(['toggle','pause','rescan'] as const).map(name => <label className="shortcut-field" key={name}>{name === 'toggle' ? 'Show / Hide' : name === 'pause' ? 'Start / Pause' : 'Rescan'}<input value={settings.shortcuts[name]} onChange={e => setSettings({ ...settings, shortcuts: { ...settings.shortcuts, [name]: e.target.value } })}/></label>)}<p className="muted">Use Electron accelerators, for example Command+Shift+H. Conflicts appear after saving; every action is also in the menu.</p></section>
      <p className="disclosure">Screen-capture protection is best effort. macOS ScreenCaptureKit may still capture these windows. Screen-sharing compatibility is unverified.</p><ErrorMessage message={error}/>{saved && <p role="status">Settings saved.{state.shortcutConflicts.length ? ` Conflicts: ${state.shortcutConflicts.join(', ')}` : ''}</p>}<div className="form-actions"><button type="button" onClick={() => window.close()}>Close</button><button className="accent-button" disabled={busy}>Save Settings</button></div>
    </form></main>;
}
function CorrectionView({ state }: { state: Snapshot }) {
  const [mode,setMode] = useState<'editor'|'fen'|'pgn'|'start'>('editor');
  const [placements,setPlacements] = useState<Placement[]>(state.observation?.placements ?? (state.position ? placementsOf(state.position.fen) : placementsOf(DEFAULT_POSITION)));
  const fields = (state.position?.fen ?? `${placementFen(placements)} w - - 0 1`).split(' ');
  const [turn,setTurn] = useState<Side>(fields[1] as Side), [rights,setRights] = useState(fields[2] === '-' ? '' : fields[2]), [ep,setEp] = useState(fields[3]), [half,setHalf] = useState(fields[4]), [full,setFull] = useState(fields[5]);
  const [side,setSide] = useState<Side>(state.position?.coachedSide ?? state.selection?.coachedSide ?? 'w'), [orientation,setOrientation] = useState<Orientation>(state.selection?.orientation ?? state.position?.orientation ?? 'white-bottom');
  const [brush,setBrush] = useState<Placement['piece'] | 'erase'>('P'), [text,setText] = useState(state.position?.fen ?? ''), [confirmed,setConfirmed] = useState(false), [previewText,setPreviewText] = useState<string | null>(null);
  const {error,busy,run} = useAction(); const fen = `${placementFen(placements)} ${turn} ${rights || '-'} ${ep || '-'} ${half || '0'} ${full || '1'}`;
  const previewImport = () => { try { const chess = new Chess(); if (mode === 'fen') chess.load(text); else chess.loadPgn(text,{strict:true}); const parts=chess.fen({forceEnpassantSquare:true}).split(' '); setPlacements(placementsOf(chess.fen())); setTurn(parts[1] as Side); setRights(parts[2]==='-'?'':parts[2]); setEp(parts[3]); setHalf(parts[4]); setFull(parts[5]); setPreviewText(text); setConfirmed(false); } catch { void run(async () => { throw new Error('The imported position is invalid. Check the complete FEN or PGN.'); }); } };
  return <main className="form-shell"><header><h1>Confirm Your Position</h1><p>Check the miniature board. A screenshot cannot establish castling rights, en passant, or earlier history.</p></header><div className="mode-buttons">{(['editor','fen','pgn','start'] as const).map(value => <button key={value} aria-pressed={mode===value} onClick={() => { setMode(value); setConfirmed(false); if(value==='start')setPlacements(placementsOf(DEFAULT_POSITION)); }}>{value==='editor'?'Edit Pieces':value==='start'?'Starting Position':value.toUpperCase()}</button>)}</div>
    <form onSubmit={e => { e.preventDefault(); void run(() => api!.correct({ ...tokenOf(state), format: mode === 'editor' ? 'fen' : mode, text: mode === 'editor' ? fen : text, coachedSide: side, orientation, confirmed: true })); }}>
      <div className="editor-layout"><Board placements={placements} orientation={orientation} onSquare={mode==='editor' ? square => { setConfirmed(false); setPlacements(current => [...current.filter(p=>p.square!==square), ...(brush==='erase' ? [] : [{square,piece:brush}])]); } : undefined}/>{mode==='editor' && <div className="palette" aria-label="Piece palette">{Object.entries(GLYPHS).map(([piece,glyph])=><button key={piece} type="button" aria-label={`Place ${piece}`} aria-pressed={brush===piece} onClick={()=>setBrush(piece as Placement['piece'])}>{glyph}</button>)}<button type="button" aria-pressed={brush==='erase'} onClick={()=>setBrush('erase')}>Erase</button></div>}</div>
      {(mode==='fen'||mode==='pgn') && <label>{mode.toUpperCase()}<textarea rows={4} value={text} onChange={e=>{setText(e.target.value);setConfirmed(false);}}/><button type="button" onClick={previewImport}>Preview Import</button></label>}
      {mode==='start' ? <p>Confirm that the browser board is the normal starting position. White moves first and all standard castling rights apply.</p> : <><div className="fields-row"><label>Side to move<select value={turn} disabled={mode!=='editor'} onChange={e=>{setTurn(e.target.value as Side);setConfirmed(false);}}><option value="w">White</option><option value="b">Black</option></select></label><label>En passant square<input value={ep} disabled={mode!=='editor'} placeholder="- or e3" onChange={e=>{setEp(e.target.value);setConfirmed(false);}}/></label></div><fieldset><legend>Castling rights — select only rights you know</legend><div className="fields-row">{['K','Q','k','q'].map(right=><label className="checkbox" key={right}><input type="checkbox" disabled={mode!=='editor'} checked={rights.includes(right)} onChange={e=>{setRights(current=>e.target.checked?['K','Q','k','q'].filter(r=>current.includes(r)||r===right).join(''):current.replace(right,''));setConfirmed(false);}}/>{right===right.toUpperCase()?'White':'Black'} {right.toLowerCase()==='k'?'kingside':'queenside'}</label>)}</div></fieldset><div className="fields-row"><label>Halfmove clock<input type="number" min="0" value={half} disabled={mode!=='editor'} onChange={e=>{setHalf(e.target.value);setConfirmed(false);}}/></label><label>Move number<input type="number" min="1" value={full} disabled={mode!=='editor'} onChange={e=>{setFull(e.target.value);setConfirmed(false);}}/></label></div></>}
      <SideControls side={side} orientation={orientation} onSide={value=>{setSide(value);setConfirmed(false);}} onOrientation={value=>{setOrientation(value);setConfirmed(false);}}/>
      {mode==='editor' && <p className="fen-output">{fen}</p>}<label className="checkbox confirmation"><input type="checkbox" required disabled={(mode==='fen'||mode==='pgn')&&previewText!==text} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the pieces, orientation, turn, castling, and en passant against the actual board.</label><ErrorMessage message={error}/><div className="form-actions"><button type="button" onClick={()=>window.close()}>Cancel</button><button className="accent-button" disabled={busy||!confirmed||((mode==='fen'||mode==='pgn')&&previewText!==text)}>Confirm & Analyze</button></div>
    </form></main>;
}
function SelectionView({ state }: { state: Snapshot }) {
  const [sources,setSources] = useState<Source[]>([]), [sourceId,setSourceId] = useState(''), [crop,setCrop] = useState<CaptureSelection['crop'] | null>(null);
  const [orientation,setOrientation] = useState<Orientation>('white-bottom'), [side,setSide] = useState<Side>('w'), [permission,setPermission] = useState('unknown');
  const video = useRef<HTMLVideoElement>(null), stream=useRef<MediaStream|null>(null), preview=useRef<HTMLDivElement>(null), epoch=useRef(0), drag=useRef<{x:number;y:number}|null>(null);
  const {error,busy,run}=useAction();
  useEffect(()=>{void run(async()=>{setPermission(await api!.screenPermission());setSources(await api!.sources(tokenOf(state)));});return()=>{++epoch.current;stream.current?.getTracks().forEach(track=>track.stop());};},[]);
  const choose=async(id:string)=>{const request=++epoch.current;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setCrop(null);setSourceId(id);await api!.selectSource({...tokenOf(state),sourceId:id});const next=await navigator.mediaDevices.getDisplayMedia({audio:false,video:{frameRate:2}});if(request!==epoch.current){next.getTracks().forEach(t=>t.stop());return;}stream.current=next;video.current!.srcObject=next;await video.current!.play();};
  const point=(event:React.PointerEvent)=>{const rect=preview.current!.getBoundingClientRect();return{x:Math.min(1,Math.max(0,(event.clientX-rect.left)/rect.width)),y:Math.min(1,Math.max(0,(event.clientY-rect.top)/rect.height))};};
  const mark=(event:React.PointerEvent)=>{if(!drag.current||!video.current?.videoWidth)return;const current=point(event),start=drag.current;const width=video.current.videoWidth,height=video.current.videoHeight;const sidePixels=Math.min(Math.abs(current.x-start.x)*width,Math.abs(current.y-start.y)*height);const cropWidth=sidePixels/width,cropHeight=sidePixels/height;setCrop({x:current.x<start.x?start.x-cropWidth:start.x,y:current.y<start.y?start.y-cropHeight:start.y,width:cropWidth,height:cropHeight});};
  return <main className="form-shell"><header><h1>Select Your Board</h1><p>Choose a Chess.com or Lichess browser window, then drag from one board corner to the opposite corner. Include exactly the 8 × 8 board.</p></header><p className="muted">Only the board crop is sent to cloud AI. No audio is captured. Screenshots stay in memory.</p>{permission==='denied' && <p className="error">Screen Recording permission is denied. Enable Chess Helper and restart the app.</p>}<div className="sources">{sources.map(source=><button disabled={busy} className={sourceId===source.id?'selected-source':''} key={source.id} onClick={()=>void run(()=>choose(source.id))}><img src={source.thumbnail} alt=""/><span>{source.name}</span></button>)}</div>{sources.length===0 && <p>No browser windows available. Open a board, check Screen Recording permission, and refresh.</p>}<div className="fields-row"><button disabled={busy} onClick={()=>void run(async()=>setSources(await api!.sources(tokenOf(state))))}>Refresh Windows</button><button onClick={()=>void run(()=>api!.openScreenSettings())}>Screen Recording Settings</button></div>
    <div ref={preview} className="capture-preview" onPointerDown={event=>{if(!stream.current)return;drag.current=point(event);event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={mark} onPointerUp={event=>{mark(event);drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><video ref={video} muted playsInline/>{crop && <div className="crop-rectangle" style={{left:`${crop.x*100}%`,top:`${crop.y*100}%`,width:`${crop.width*100}%`,height:`${crop.height*100}%`}}/>}{!sourceId && <span>Select a window to see its preview</span>}</div>
    <SideControls side={side} orientation={orientation} onSide={setSide} onOrientation={setOrientation}/><ErrorMessage message={error}/><div className="form-actions"><button onClick={()=>window.close()}>Cancel</button><button className="accent-button" disabled={busy||!crop||crop.width<.02||crop.height<.02} onClick={()=>void run(async()=>{const selection={...tokenOf(state),sourceId,crop:crop!,orientation,coachedSide:side,sourceWidth:video.current!.videoWidth,sourceHeight:video.current!.videoHeight};stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;try { await api!.selectBoard(selection); } catch (error) { setSourceId(''); setCrop(null); throw error; }})}>Read This Board</button></div></main>;
}
function App(){const state=useSnapshot();const view=new URLSearchParams(location.search).get('view')??'coach';useEffect(()=>{document.body.classList.toggle('coaching-window',view==='coach');},[view]);if(!api)return <main className="form-shell"><h1>Chess Helper</h1><p>Open the Electron app to select a board and analyze positions.</p><Board placements={placementsOf(DEFAULT_POSITION)} orientation="white-bottom"/></main>;if(!state)return <main className="form-shell" role="status">Loading Chess Helper…</main>;return view==='settings'?<SettingsView state={state}/>:view==='correction'?<CorrectionView state={state}/>:view==='selection'?<SelectionView state={state}/>:<Coach state={state}/>;}
createRoot(document.getElementById('root')!).render(<App/>);
